<a href="https://colab.research.google.com/github/2303a51519/hemanth/blob/main/assignment%201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
l = []
n = int(input("Enter No.of elements in a list : "))
while (n>0):
  e = int(input("Enter element : "))
  l.append(e)
  n-=1
print(l)
arr1 = np.array(l)
print(type(l))
print(arr1)
print(type(arr1))
m = []
n = int(input("Enter No.of elements in a list : "))
while (n>0):
  e = int(input("Enter element : "))
  m.append(e)
  n-=1
print(m)
arr2 = np.array(m)
print(type(m))
print(arr2)
print(type(arr2))
print("Multiplication : ",arr1*arr2)
print("Division : ",arr1/arr2)
print("Exponent : ",arr1**arr2)
print("Addition : ",arr1+arr2)
p = np.sin(arr1)
q = np.log(arr1)
r = np.log2(arr2)
s = np.exp(arr1)
print(p)
print(q)
print(r)
print(s)
st1 = "Vineeth"
st2 = " Puneriya"
print(st1+st2)

Enter No.of elements in a list : 3
Enter element : 1
Enter element : 2
Enter element : 3
[1, 2, 3]
<class 'list'>
[1 2 3]
<class 'numpy.ndarray'>
Enter No.of elements in a list : 3
Enter element : 3
Enter element : 6
Enter element : 9
[3, 6, 9]
<class 'list'>
[3 6 9]
<class 'numpy.ndarray'>
Multiplication :  [ 3 12 27]
Division :  [0.33333333 0.33333333 0.33333333]
Exponent :  [    1    64 19683]
Addition :  [ 4  8 12]
[0.84147098 0.90929743 0.14112001]
[0.         0.69314718 1.09861229]
[1.5849625 2.5849625 3.169925 ]
[ 2.71828183  7.3890561  20.08553692]
Vineeth Puneriya
